### PR TITLE
add some foundation related resources

### PR DESCRIPTION
**Pull request by ldpliu**
Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/stolostron/backlog/issues/25468

### CODE REVIEW

**Comment by ldpliu** [comment]
@JakobGray and @eemurphy 
I added some foundation/clc related resources in must-gather, please help to review this pr,

**Comment by eemurphy** [comment]
@ldpliu Could you also add this change [here](https://github.com/stolostron/must-gather/blob/main/collection-scripts/mce-gather.sh)? In 2.8 we're requiring any mce must-gather changes to be duplicated in that script as well

**Comment by ldpliu** [comment]
Thanks @eemurphy 
I have summited the pr in : https://github.com/stolostron/must-gather/pull/139

BTW: If it is possible to use a cron job to sync the script ?

**Review by eemurphy — APPROVED** [review]
@ldpliu we can look into that it may be possible. In the meantime thank you for the 2nd PR, I will approve both now!

**Pull request merged**
